version: "3"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=queries_challenge
    restart: always
    ports:
      - 5432:5432
    network_mode: host
